In [1]:
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

# Remplacez 'Mon_Dossier/mon_fichier.csv' par le chemin réel de votre fichier sur Google Drive
file_path = '/content/drive/My Drive/formation_personnelle/data_csv/base_produits.csv'

try:
    df = pd.read_csv(file_path, sep=";", encoding='latin1')
    print(f"Fichier '{file_path}' chargé avec succès.")
    display(df.head())
except FileNotFoundError:
    print(f"Erreur: Le fichier '{file_path}' n'a pas été trouvé. Veuillez vérifier le chemin.")
except Exception as e:
    print(f"Une erreur est survenue lors du chargement du fichier: {e}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Fichier '/content/drive/My Drive/formation_personnelle/data_csv/base_produits.csv' chargé avec succès.

  id_produit    prix  catégorie
0      P0001  471,86          0
1      P0002  422,52          1
2      P0003   342,7          4
3      P0004  437,88          0
4      P0005  205,03          3

In [5]:
produit = df

In [7]:
produit['catégorie'] = produit['catégorie'].replace(0, 'categ 0')
produit['catégorie'] = produit['catégorie'].replace(1, 'categ 1')
produit['catégorie'] = produit['catégorie'].replace(2, 'categ 2')
produit['categorie'] = produit['catégorie'].replace(3, 'categ 3')
produit['categorie'] = produit['categorie'].replace(4, 'categ 4')
produit['categorie'] = produit['categorie'].replace(5, 'categ 5')
produit

    id_produit    prix    catégorie    categorie
0        P0001  471,86  categorie 0  categorie 0
1        P0002  422,52  categorie 1  categorie 1
2        P0003   342,7            4      categ 4
3        P0004  437,88  categorie 0  categorie 0
4        P0005  205,03            3      categ 3
..         ...     ...          ...          ...
255      P0256  433,27  categorie 0  categorie 0
256      P0257    88,9            3      categ 3
257      P0258  109,93  categorie 2  categorie 2
258      P0259  229,69            3      categ 3
259      P0260  427,66            4      categ 4

[260 rows x 4 columns]